services:
  iris:
    build: ./image-iris
    platform: linux/amd64
    depends_on:
      - plc
    hostname: iris
    init: true
    ports:
      - "51793:1972"     # superserver (vanilla IRIS uses 1972)
      - "52783:52773"    # web server / management portal

  plc:
    hostname: plc
    init: true
    image: intersystemsdc/opcua-mockserver:version-0.3.0
    ports:
      - "10000:4840"
    volumes:
      - type: bind
        source: ./mocksvr-data/
        target: /app/data

  certified-server:
    build: ./image-opcua-certified-server
    hostname: certified-server
    init: true
    ports:
      - "10001:4840"
